spring.application.name=real-time-app_backend

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/realtime_app
spring.datasource.username=root
spring.datasource.password=Panditg@11111

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

jwt.secret=RealTimeCommunicationApplicationSecretKey2026
jwt.expiration=86400000
